package org.qualsh.lb.digitalmodes.view;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.File;

/**
 * A toolbar-style panel that provides the operator with complete control over
 * audio input for the Digital Modes feature.
 *
 * <p>The panel exposes six transport controls — Upload WAV, Record,
 * Stop Recording, Play, Pause, Stop — along with a Loop toggle and a status
 * label. All user actions are dispatched to a registered
 * {@link AudioControlListener} so that the parent window can wire the controls
 * to the audio subsystem without coupling directly to this panel's
 * implementation.
 *
 * <p>Call {@link #setAudioControlListener(AudioControlListener)} once after
 * construction to connect the panel to the rest of the Digital Modes
 * infrastructure.
 */
public class AudioControlPanel extends JPanel {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Listener interface
    // -------------------------------------------------------------------------

    /**
     * Callback interface for components that need to react to audio control
     * events generated by an {@link AudioControlPanel}.
     *
     * <p>All methods are invoked on the Swing Event Dispatch Thread.
     */
    public interface AudioControlListener {

        /**
         * Called after the operator has selected a WAV file to import.
         *
         * @param file the WAV file chosen in the file dialog; never
         *             {@code null}
         */
        void onFileUploaded(File file);

        /**
         * Called when the operator has chosen an output path and started
         * live microphone recording.
         *
         * @param outputFile the file where captured audio will be written;
         *                   never {@code null}
         */
        void onRecordStarted(File outputFile);

        /**
         * Called when the operator clicks <em>Stop Recording</em> to end a
         * live capture session.
         */
        void onRecordStopped();

        /**
         * Called when the operator clicks <em>Play</em> to start or resume
         * audio playback.
         */
        void onPlayClicked();

        /**
         * Called when the operator clicks <em>Pause</em> to pause playback
         * at the current position.
         */
        void onPauseClicked();

        /**
         * Called when the operator clicks <em>Stop</em> to halt playback and
         * reset the position to the beginning.
         */
        void onStopClicked();

        /**
         * Called when the operator toggles the Loop button.
         *
         * @param looping {@code true} if loop playback is now enabled;
         *                {@code false} if it has been turned off
         */
        void onLoopToggled(boolean looping);
    }

    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------

    private final JButton       uploadButton;
    private final JButton       recordButton;
    private final JButton       stopRecordButton;
    private final JButton       playButton;
    private final JButton       pauseButton;
    private final JButton       stopButton;
    private final JToggleButton loopButton;
    private final JLabel        statusLabel;

    private AudioControlListener listener;

    // -------------------------------------------------------------------------
    // Construction
    // -------------------------------------------------------------------------

    /**
     * Creates an {@code AudioControlPanel} with all controls initialised.
     *
     * <p>The <em>Stop Recording</em> button is disabled at startup because
     * there is no active recording to stop. All other controls are enabled.
     * The panel uses a left-aligned {@link FlowLayout} with a 6-pixel gap
     * between components.
     */
    public AudioControlPanel() {
        setLayout(new FlowLayout(FlowLayout.LEFT, 6, 4));

        uploadButton     = new JButton("Upload WAV");
        recordButton     = new JButton("Record");
        stopRecordButton = new JButton("Stop Recording");
        playButton       = new JButton("\u25B6 Play");
        pauseButton      = new JButton("\u23F8 Pause");
        stopButton       = new JButton("\u23F9 Stop");
        loopButton       = new JToggleButton("\u27F3 Loop");
        statusLabel      = new JLabel("No file loaded");

        stopRecordButton.setEnabled(false);

        add(uploadButton);
        add(recordButton);
        add(stopRecordButton);
        add(new JSeparator(SwingConstants.VERTICAL));
        add(playButton);
        add(pauseButton);
        add(stopButton);
        add(loopButton);
        add(new JSeparator(SwingConstants.VERTICAL));
        add(statusLabel);

        attachListeners();
    }

    // -------------------------------------------------------------------------
    // Internal listeners
    // -------------------------------------------------------------------------

    private void attachListeners() {

        uploadButton.addActionListener(e -> {
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Select WAV File");
            chooser.setFileFilter(new FileNameExtensionFilter("WAV Audio Files (*.wav)", "wav"));
            int result = chooser.showOpenDialog(AudioControlPanel.this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                statusLabel.setText(file.getName());
                if (listener != null) {
                    listener.onFileUploaded(file);
                }
            }
        });

        recordButton.addActionListener(e -> {
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Save Recording As");
            chooser.setFileFilter(new FileNameExtensionFilter("WAV Audio Files (*.wav)", "wav"));
            chooser.setSelectedFile(new File(System.getProperty("user.home"), "recording.wav"));
            int result = chooser.showSaveDialog(AudioControlPanel.this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                if (!file.getName().toLowerCase().endsWith(".wav")) {
                    file = new File(file.getAbsolutePath() + ".wav");
                }
                recordButton.setEnabled(false);
                stopRecordButton.setEnabled(true);
                statusLabel.setText("Recording...");
                if (listener != null) {
                    listener.onRecordStarted(file);
                }
            }
        });

        stopRecordButton.addActionListener(e -> {
            recordButton.setEnabled(true);
            stopRecordButton.setEnabled(false);
            statusLabel.setText("Recording saved");
            if (listener != null) {
                listener.onRecordStopped();
            }
        });

        playButton.addActionListener(e -> {
            if (listener != null) {
                listener.onPlayClicked();
            }
        });

        pauseButton.addActionListener(e -> {
            if (listener != null) {
                listener.onPauseClicked();
            }
        });

        stopButton.addActionListener(e -> {
            if (listener != null) {
                listener.onStopClicked();
            }
        });

        loopButton.addActionListener(e -> {
            if (listener != null) {
                listener.onLoopToggled(loopButton.isSelected());
            }
        });
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Registers the listener that receives audio control events from this panel.
     *
     * <p>Passing {@code null} removes any previously registered listener and
     * silently disables all callbacks until a new listener is set.
     *
     * @param listener the listener to register, or {@code null} to deregister
     */
    public void setAudioControlListener(AudioControlListener listener) {
        this.listener = listener;
    }

    /**
     * Returns the status label component so that external code can update the
     * displayed text directly when needed (for example, after an asynchronous
     * file-load completes).
     *
     * @return the status label; never {@code null}
     */
    public JLabel getStatusLabel() {
        return statusLabel;
    }
}
